library(tidyverse)
install.packages("palmerpenguins")
penguins %>% arrange(bill_length_mm)
library(palmerpenguins)
penguins %>% arrange(bill_length_mm)
penguins %>% arrange(-bill_length_mm)
penguins2 <- penguins %>% arrange(-bill_length_mm)
penguins2 <- penguins %>% arrange(-bill_length_mm)
view()
penguins2 <- penguins %>% arrange(-bill_length_mm)
view(penguins2)
penguins %>% group_by(island) %>% drop_na() %>% summarize(mean_bill_length_mm= mean(bill_length_mm))
penguins %>% group_by(island) %>% drop_na() %>% summarize(max_bill_length_mm= max(bill_length_mm))
penguins %>% group_by(species,island) %>% drop_na() %>% summarize(max_b1= max(bill_length_mm), mean_b1 = mean(bill_length_mm))
penguins %>% flter(species == "Adelie")
